// filepath: /d:/Development/Career Climb/client/src/Component/CareerGraphComponents/Data.jsx
const Nodes = [
    { id: '1', data: { label: 'Software Developer' }, position: { x: 100, y: 50 }, type: 'input' },
    { id: '2', data: { label: 'Web Developer' }, position: { x: 200, y: 100 } },
    { id: '3', data: { label: 'Mobile Developer' }, position: { x: 300, y: 150 } },
    { id: '4', data: { label: 'Data Scientist' }, position: { x: 400, y: 200 } },
    { id: '5', data: { label: 'Machine Learning Engineer' }, position: { x: 500, y: 250 } },
    { id: '6', data: { label: 'Data Analyst' }, position: { x: 600, y: 300 } },
    { id: '7', data: { label: 'Cloud Engineer' }, position: { x: 700, y: 350 } },
    { id: '8', data: { label: 'Cyber Security Analyst' }, position: { x: 800, y: 400 } },
    { id: '9', data: { label: 'Software Engineer' }, position: { x: 900, y: 450 } },
    { id: '10', data: { label: 'Network Engineer' }, position: { x: 1000, y: 500 } },
    { id: '11', data: { label: 'Database Administrator' }, position: { x: 1100, y: 550 } },
    { id: '12', data: { label: 'Systems Analyst' }, position: { x: 1200, y: 600 } },
    { id: '13', data: { label: 'Computer Systems Analyst' }, position: { x: 1300, y: 650 } },
    { id: '14', data: { label: 'IT Manager' }, position: { x: 1400, y: 700 } },
    { id: '15', data: { label: 'IT Consultant' }, position: { x: 1500, y: 750 } },
    { id: '16', data: { label: 'Computer Systems Administrator' }, position: { x: 1600, y: 800 } },
    { id: '17', data: { label: 'Computer Systems Engineer' }, position: { x: 1700, y: 850 } },
    { id: '18', data: { label: 'Computer Systems Manager' }, position: { x: 1800, y: 900 } },
    { id: '19', data: { label: 'Computer Systems Architect' }, position: { x: 1900, y: 950 } },
    { id: '20', data: { label: 'Computer Systems Designer' }, position: { x: 2000, y: 1000 } },
    { id: '21', data: { label: 'Computer Systems Developer' }, position: { x: 2100, y: 1050 } },
    { id: '22', data: { label: 'Computer Systems Programmer' }, position: { x: 2200, y: 1100 } },
    { id: '23', data: { label: 'Computer Systems Manager' }, position: { x: 2300, y: 1150 } },
    { id: '24', data: { label: 'Computer Systems Architect' }, position: { x: 2400, y: 1200 } },
    { id: '25', data: { label: 'Computer Systems Designer' }, position: { x: 2500, y: 1250 } },
    { id: '26', data: { label: 'Computer Systems Developer' }, position: { x: 2600, y: 1300 } },
    { id: '27', data: { label: 'Computer Systems Programmer' }, position: { x: 2700, y: 1350 } },
    { id: '28', data: { label: 'Computer Systems Manager' }, position: { x: 2800, y: 1400 } },
    { id: '29', data: { label: 'Computer Systems Architect' }, position: { x: 2900, y: 1450 } },
    { id: '30', data: { label: 'Computer Systems Designer' }, position: { x: 3000, y: 1500 } },
    { id: '31', data: { label: 'Computer Systems Developer' }, position: { x: 3100, y: 1550 } },
    { id: '32', data: { label: 'Computer Systems Programmer' }, position: { x: 3200, y: 1600 } },
    { id: '33', data: { label: 'Computer Systems Manager' }, position: { x: 3300, y: 1650 } },
    { id: '34', data: { label: 'Computer Systems Architect' }, position: { x: 3400, y: 1700 } },
    { id: '35', data: { label: 'Computer Systems Designer' }, position: { x: 3500, y: 1750 } },
    { id: '36', data: { label: 'Computer Systems Developer' }, position: { x: 3600, y: 1800 } },
    { id: '37', data: { label: 'Computer Systems Programmer' }, position: { x: 3700, y: 1850 } },
    { id: '38', data: { label: 'Computer Systems Manager' }, position: { x: 3800, y: 1900 } },
    { id: '39', data: { label: 'Computer Systems Architect' }, position: { x: 3900, y: 1950 } },
    { id: '40', data: { label: 'Computer Systems Designer' }, position: { x: 4000, y: 2000 } },
    { id: '41', data: { label: 'Computer Systems Developer' }, position: { x: 4100, y: 2050 } },
    { id: '42', data: { label: 'Computer Systems Programmer' }, position: { x: 4200, y: 2100 } },
    { id: '43', data: { label: 'Computer Systems Manager' }, position: { x: 4300, y: 2150 } },
    { id: '44', data: { label: 'Computer Systems Architect' }, position: { x: 4400, y: 2200 } },
    { id: '45', data: { label: 'Computer Systems Designer' }, position: { x: 4500, y: 2250 } },
    { id: '46', data: { label: 'Computer Systems Developer' }, position: { x: 4600, y: 2300 } },
    { id: '47', data: { label: 'Computer Systems Programmer' }, position: { x: 4700, y: 2350 } },
    { id: '48', data: { label: 'Computer Systems Manager' }, position: { x: 4800, y: 2400 } },
    { id: '49', data: { label: 'Computer Systems Architect' }, position: { x: 4900, y: 2450 } },
    { id: '50', data: { label: 'Computer Systems Designer' }, position: { x: 5000, y: 2500 } },
    { id: '51', data: { label: 'Computer Systems Developer' }, position: { x: 5100, y: 2550 } },
    { id: '52', data: { label: 'Computer Systems Programmer' }, position: { x: 5200, y: 2600 } },
    { id: '53', data: { label: 'Computer Systems Manager' }, position: { x: 5300, y: 2650 } },
    { id: '54', data: { label: 'Computer Systems Architect' }, position: { x: 5400, y: 2700 } },
    { id: '55', data: { label: 'Computer Systems Designer' }, position: { x: 5500, y: 2750 } },
    { id: '56', data: { label: 'Computer Systems Developer' }, position: { x: 5600, y: 2800 } },
];

function getRandomInt(max) {
    return Math.floor(Math.random() * max) + 1;
}

const Edges = [
    { id: 'e1-2', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e2-3', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e3-4', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e4-5', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e5-6', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e6-7', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e7-8', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e8-9', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e9-10', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e10-11', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e11-12', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e12-13', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e13-14', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e14-15', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e15-16', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e16-17', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e17-18', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e18-19', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e19-20', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e20-21', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e21-22', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e22-23', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e23-24', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e24-25', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e25-26', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e26-27', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e27-28', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e28-29', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e29-30', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e30-31', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() },
    { id: 'e31-32', source: getRandomInt(56).toString(), target: getRandomInt(56).toString() }
];

export { Nodes, Edges };